name: "Pipeline CI-CD"
run-name: "Pipeline executada pelo ${{ github.actor }}"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo arquivos do projeto
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Execucao do comando buils
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  # testes_qa:
   # needs: [build]
   # uses: fspelling/desafio-cicd-01/.github/workflows/testes.yml@main
   # secrets: inherit
  release:
   # needs: [testes_qa]
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo arquivos do projeto
        uses: actions/checkout@v4
      - name: Analise dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile
      - name: Autenticacao no Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Build/Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            fspelling/projeto-devops-pro:latest
            fspelling/projeto-devops-pro:v${{ github.run_number }}
      - name: Scan trivy
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'image'
          image-ref: fspelling/projeto-devops-pro:v${{ github.run_number }}
          format: sarif
          output: trivy-docker-result-full.sarif
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - name: Publicando vulnerabilidades
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: 'trivy-result'
          sarif_file: trivy-docker-result-full.sarif
  deploy_hml:
    needs: [release]
    uses: fspelling/desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment_name: hml
      environment_url: http://hml.fspelling.com
  # teste_e2e:
  #   needs: [deploy_hml]
  #   runs-on: ubuntu-latest
  #   environment: hml
  #   container:
  #     image: fabricioveronez/webdriver-dotnet:chrome
  #     env:
  #       BASE_URL: "http://${{ vars.K8S_BASE_URL }}"
  #   steps:
  #     - name: "Obtendo arquivos do projeto"
  #       uses: actions/checkout@v4
  #     - name: "Execucao testes e2e"
  #       working-directory: ./src
  #       run: dotnet test ./Review-Filmes.Test.EndToEnd/Review-Filmes.Test.EndToEnd.csproj
  deploy_prd:
    needs: [deploy_hml]
    uses: fspelling/desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment_name: prd
      environment_url: http://prd.fspelling.com
