name: "Pipeline CI-CD"
run-name: "Pipeline executada pelo ${{ github.actor }}"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo arquivos do projeto
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Execucao do comando buils
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  # testes_qa:
   # needs: [build]
   # uses: fspelling/desafio-cicd-01/.github/workflows/testes.yml@main
   # secrets: inherit
  release:
   # needs: [testes_qa]
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo arquivos do projeto
        uses: actions/checkout@v4
      - name: Analise dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile
      - name: Autenticacao no Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Build/Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            fspelling/projeto-devops-pro:latest
            fspelling/projeto-devops-pro:v${{ github.run_number }}
      - name: Scan trivy
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'image'
          image-ref: fspelling/projeto-devops-pro:v${{ github.run_number }}
          format: sarif
          output: trivy-docker-result.sarif
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          exit-code: 1
      - name: Publicando vulnerabilidades
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: 'trivy-result'
          sarif_file: trivy-docker-result.sarif
